### ISSUE TITLE
hinject 

### ISSUE THREAD

**Issue by sabeesh03** [dwisiswant0/hinject#1]
hi
hinject % echo "https://hackerone.com/" | hinject
zsh: command not found: hinject

**Comment by dwisiswant0** [comment]
Please provide screenshots.

Simple usage:
`echo "https://hackerone.com/" | hinject`

**Comment by sabeesh03** [comment]
![Screenshot 2020-06-01 at 2 37 38 AM](https://user-images.githubusercontent.com/49208444/83362723-1714cf00-a3b1-11ea-914e-f01c4ab54130.png)
