### ISSUE TITLE
stops running after sometime

### ISSUE THREAD

**Issue by MR-pentestGuy** [dwisiswant0/hinject#3]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x656e76]

goroutine 6 [running]:
main.main.func1(0xc000014310, 0x0, 0x0, 0x6d9194, 0x2e, 0xc000014308, 0xc000078ba0)

**Comment by dwisiswant0** [comment]
Can you please give detailed screenshots, @MR-pentestGuy?

**Comment by tanetane2** [comment]
same situation here :)
<img width="686" alt="Screenshot 2020-11-26 at 19 05 43" src="https://user-images.githubusercontent.com/65550037/100381915-63686100-301a-11eb-93ef-3c5bd5997038.png">
